name: MY First Workflow
on: push

env:
  port: 8000
  screcetno: Helloworld123

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Environment variables
        run: echo ${{ env.port }}
      - name: Variable2
        run: echo $screcetno 
