name: MY First Workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps: 
      - name: Running Lint
        run: echo "Lint..."
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: src-files
          path: |
            src
            package.json
            
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "Deploying..."
      



        
