name: MY First Workflow
on: push

env:
  port: 8000
  screcetno: Helloworld123
  awssecret: test@123
  mydate: $(openssl rand -hex 4)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Environment variables
        run: echo ${{ env.port }}
      - name: Variable2
        run: echo $screcetno 
      - name: Variable3
        run: echo '${{ env.awssecret }}'
      - name: Variable4
        run: echo '${{ env.mydate }}'
      - name: Variable5
        run: echo $mydate'                         
